# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x05zchat\x1a\x1fgoogle/protobuf/timestamp.proto\"/\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\">\n\x0bUserCreated\x12\x14\n\x0c\x63onfirmation\x18\x01 \x01(\t\x12\x19\n\x04user\x18\x02 \x01(\x0b\x32\x0b.zchat.User\"K\n\x11\x43reateChatRequest\x12\x1a\n\x05user1\x18\x01 \x01(\x0b\x32\x0b.zchat.User\x12\x1a\n\x05user2\x18\x02 \x01(\x0b\x32\x0b.zchat.User\"H\n\x04\x43hat\x12\x0f\n\x07\x63hat_id\x18\x01 \x01(\x05\x12\x11\n\tchat_name\x18\x02 \x01(\t\x12\r\n\x05user1\x18\x03 \x01(\x05\x12\r\n\x05user2\x18\x04 \x01(\x05\"\x93\x01\n\x07Message\x12\x0f\n\x07\x63hat_id\x18\x01 \x01(\x05\x12\x11\n\tsender_id\x18\x02 \x01(\x05\x12\x13\n\x0breceiver_id\x18\x03 \x01(\x05\x12\x12\n\nmessage_id\x18\x04 \x01(\x05\x12\x0c\n\x04text\x18\x05 \x01(\t\x12-\n\ttimestamp\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"*\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t2=\n\nCreateUser\x12/\n\nCreateUser\x12\x0b.zchat.User\x1a\x12.zchat.UserCreated\"\x00\x32z\n\x0bSendMessage\x12\x39\n\nCreateChat\x12\x18.zchat.CreateChatRequest\x1a\x0f.zchat.Response\"\x00\x12\x30\n\x0bSendMessage\x12\x0e.zchat.Message\x1a\x0f.zchat.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USER']._serialized_start=54
  _globals['_USER']._serialized_end=101
  _globals['_USERCREATED']._serialized_start=103
  _globals['_USERCREATED']._serialized_end=165
  _globals['_CREATECHATREQUEST']._serialized_start=167
  _globals['_CREATECHATREQUEST']._serialized_end=242
  _globals['_CHAT']._serialized_start=244
  _globals['_CHAT']._serialized_end=316
  _globals['_MESSAGE']._serialized_start=319
  _globals['_MESSAGE']._serialized_end=466
  _globals['_RESPONSE']._serialized_start=468
  _globals['_RESPONSE']._serialized_end=510
  _globals['_CREATEUSER']._serialized_start=512
  _globals['_CREATEUSER']._serialized_end=573
  _globals['_SENDMESSAGE']._serialized_start=575
  _globals['_SENDMESSAGE']._serialized_end=697
# @@protoc_insertion_point(module_scope)
